version: '2'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable

  dev2:
    build:
      context:  ./
      dockerfile: Dockerfile.dev2

  stable2:
    build:
      context: ./
      dockerfile: Dockerfile.stable2
